// ─── StyleHub Mock Data ──────────────────────────────────────────────────────
// Replace with real API calls via fetch() in Server Components

export interface Category {
  id:          string;
  name:        string;
  slug:        string;
  image:       string;
  productCount:number;
  gradient:    string;
}

export interface Vendor {
  id:          string;
  name:        string;
  slug:        string;
  logo:        string;
  banner:      string;
  description: string;
  rating:      number;
  reviewCount: number;
  productCount:number;
  location:    string;
  tags:        string[];
  verified:    boolean;
}

export interface ProductVariant {
  size:     string;
  color:    string;
  colorHex: string;
  stock:    number;
  price:    number;   // effective price for this variant (defaults to basePrice)
  sku:      string;
}

export interface Review {
  id:        string;
  author:    string;
  avatar:    string;
  rating:    number;
  date:      string;
  title:     string;
  body:      string;
  verified:  boolean;
  helpful:   number;
  images?:   string[];
}

export interface Product {
  id:              string;
  name:            string;
  slug:            string;
  brand:           string;
  category:        string;
  categorySlug:    string;
  vendor:          Vendor;
  // Shortcut fields derived from vendor (used in cart store)
  vendorId:        string;
  vendorName:      string;
  vendorSlug:      string;
  description:     string;
  longDescription: string;
  images:          string[];
  basePrice:       number;
  compareAtPrice?: number;
  rating:          number;
  reviewCount:     number;
  soldCount:       number;
  gender:          string;
  tags:            string[];
  material:        string;
  careInstructions:string;
  variants:        ProductVariant[];
  reviews:         Review[];
  isFeatured:      boolean;
  isNew:           boolean;
  isBestSeller:    boolean;
  isTrending?:     boolean;
}

// ─── Vendors ─────────────────────────────────────────────────────────────────
export const VENDORS: Vendor[] = [
  {
    id: 'v1', name: 'UrbanThreads', slug: 'urban-threads',
    logo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=80&h=80&fit=crop',
    banner: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=1200&h=400&fit=crop',
    description: 'Premium everyday wear crafted from sustainable fabrics. Where comfort meets conscious fashion.',
    rating: 4.8, reviewCount: 1240, productCount: 312, location: 'Mumbai, India',
    tags: ['Sustainable', 'Minimalist', 'Premium Cotton'], verified: true,
  },
  {
    id: 'v2', name: 'DesiCouture', slug: 'desi-couture',
    logo: 'https://images.unsplash.com/photo-1610473228636-7a2e4bf0c37a?w=80&h=80&fit=crop',
    banner: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=1200&h=400&fit=crop',
    description: 'Celebrating the art of Indian craftsmanship with contemporary silhouettes.',
    rating: 4.7, reviewCount: 986, productCount: 278, location: 'Jaipur, India',
    tags: ['Ethnic', 'Handcrafted', 'Luxury'], verified: true,
  },
  {
    id: 'v3', name: 'SoleMate', slug: 'sole-mate',
    logo: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=80&h=80&fit=crop',
    banner: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=1200&h=400&fit=crop',
    description: 'Where every step tells a story. Handcrafted footwear from the finest leathers.',
    rating: 4.6, reviewCount: 754, productCount: 201, location: 'Agra, India',
    tags: ['Handcrafted', 'Leather', 'Artisan'], verified: true,
  },
  {
    id: 'v4', name: 'GlimmerCo', slug: 'glimmerco',
    logo: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=80&h=80&fit=crop',
    banner: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=1200&h=400&fit=crop',
    description: 'Fine fashion jewellery and luxury accessories curated for the discerning shopper.',
    rating: 4.8, reviewCount: 890, productCount: 145, location: 'Chennai, India',
    tags: ['Jewellery', 'Bags', 'Luxury'], verified: true,
  },
  {
    id: 'v5', name: 'VelveteenRose', slug: 'velveteen-rose',
    logo: 'https://images.unsplash.com/photo-1533659124865-d6072dc035e1?w=80&h=80&fit=crop',
    banner: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=1200&h=400&fit=crop',
    description: 'Boho-chic kaftans, tops and loungewear inspired by the coastal lifestyle.',
    rating: 4.7, reviewCount: 420, productCount: 95, location: 'Goa, India',
    tags: ['Kaftans', 'Boho', 'Resort'], verified: true,
  },
];

// ─── Categories ───────────────────────────────────────────────────────────────
export const CATEGORIES: Category[] = [
  { id: 'c1', name: 'Dresses',     slug: 'dresses',     image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&h=500&fit=crop', productCount: 284, gradient: 'from-rose-900/70 to-rose-600/40' },
  { id: 'c2', name: 'Tops',        slug: 'tops',        image: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=400&h=500&fit=crop', productCount: 512, gradient: 'from-amber-900/70 to-amber-600/40' },
  { id: 'c3', name: 'Ethnic Wear', slug: 'ethnic',      image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=400&h=500&fit=crop', productCount: 198, gradient: 'from-purple-900/70 to-purple-600/40' },
  { id: 'c4', name: 'Footwear',    slug: 'footwear',    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=500&fit=crop', productCount: 167, gradient: 'from-stone-900/70 to-stone-600/40' },
  { id: 'c5', name: 'Accessories', slug: 'accessories', image: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=500&fit=crop', productCount: 340, gradient: 'from-teal-900/70 to-teal-600/40' },
  { id: 'c6', name: 'Denim',       slug: 'denim',       image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=500&fit=crop', productCount: 143, gradient: 'from-blue-900/70 to-blue-600/40' },
  { id: 'c7', name: 'Co-ord Sets', slug: 'coords',      image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&h=500&fit=crop', productCount: 89,  gradient: 'from-cyan-900/70 to-cyan-600/40' },
  { id: 'c8', name: 'Kaftans',     slug: 'kaftans',     image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&h=500&fit=crop', productCount: 74,  gradient: 'from-orange-900/70 to-orange-600/40' },
  { id: 'c9', name: 'Shirts',      slug: 'shirts',      image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=500&fit=crop', productCount: 120, gradient: 'from-sky-900/70 to-sky-600/40' },
];

// ─── Mock Reviews ──────────────────────────────────────────────────────────────
const SAMPLE_REVIEWS: Review[] = [
  { id: 'r1', author: 'Priya M.', avatar: 'P', rating: 5, date: '12 Jul 2026', title: 'Absolutely stunning!', body: 'The fabric quality is incredible. Fits perfectly and the colour is even more beautiful in person. Will definitely order again!', verified: true, helpful: 24 },
  { id: 'r2', author: 'Ananya S.', avatar: 'A', rating: 4, date: '8 Jul 2026', title: 'Great quality, slightly large', body: 'Love the design and fabric but I should have sized down. The details are exquisite though. Customer service was very helpful.', verified: true, helpful: 11 },
  { id: 'r3', author: 'Riya K.', avatar: 'R', rating: 5, date: '3 Jul 2026', title: 'Perfect for festive season', body: 'Ordered this for a wedding and received SO many compliments. The embroidery work is gorgeous. Packaging was also very premium.', verified: true, helpful: 38 },
  { id: 'r4', author: 'Neha T.', avatar: 'N', rating: 4, date: '28 Jun 2026', title: 'Beautiful piece', body: 'Very well made. The stitching is clean and the colours are vibrant. Delivery was faster than expected too!', verified: false, helpful: 7 },
];

const RAW_PRODUCTS = [
  {
    id: 'p1',
    name: "Traditional Indigo Block Print Kurta",
    slug: 'traditional-indigo-block-print-kurta',
    brand: 'DesiCouture',
    category: 'Ethnic Wear',
    categorySlug: 'ethnic',
    vendor: VENDORS[1]!,
    description: "Handcrafted cotton kurta in deep indigo with traditional Rajasthani block print. Relaxed and lightweight.",
    longDescription: "Handcrafted cotton kurta in deep indigo with traditional Rajasthani block print. Relaxed and lightweight. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1564463836146-4e30522c2984?w=800", "https://images.unsplash.com/photo-1614251056818-9d1e71a685bb?w=800"],
    basePrice: 1899,
    rating: 4.7,
    reviewCount: 94,
    soldCount: 30,
    gender: 'men',
    tags: ["ethnic", "kurta", "men", "block-print"],
    material: '100% Khadi Cotton',
    careInstructions: 'Hand wash cold. Dry in shade.',
    variants: [
      { size: 'S', color: 'Indigo', image: '/images/products/traditional-indigo-block-print-kurta.png', colorHex: '#1E3A8A', stock: 25, sku: 'DC-MKR-001-S' },
      { size: 'M', color: 'Indigo', image: '/images/products/traditional-indigo-block-print-kurta.png', colorHex: '#1E3A8A', stock: 30, sku: 'DC-MKR-001-M' },
      { size: 'L', color: 'Indigo', image: '/images/products/traditional-indigo-block-print-kurta.png', colorHex: '#1E3A8A', stock: 20, sku: 'DC-MKR-001-L' },
      { size: 'XL', color: 'Indigo', image: '/images/products/traditional-indigo-block-print-kurta.png', colorHex: '#1E3A8A', stock: 15, sku: 'DC-MKR-001-XL' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p2',
    name: "Breezy Classic Linen Shirt",
    slug: 'breezy-classic-linen-shirt',
    brand: 'UrbanThreads',
    category: 'Shirts',
    categorySlug: 'shirts',
    vendor: VENDORS[0]!,
    description: "Breezy and comfortable white linen shirt with a classic collar. Perfect for everyday casual wear.",
    longDescription: "Breezy and comfortable white linen shirt with a classic collar. Perfect for everyday casual wear. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800"],
    basePrice: 2199,
    rating: 4.8,
    reviewCount: 128,
    soldCount: 37,
    gender: 'men',
    tags: ["shirt", "linen", "men", "casual"],
    material: '100% Pure Linen',
    careInstructions: 'Machine wash cold. Warm iron.',
    variants: [
      { size: 'S', color: 'White', colorHex: '#FFFFFF', stock: 40, sku: 'UT-WLS-001-S' },
      { size: 'M', color: 'White', colorHex: '#FFFFFF', stock: 50, sku: 'UT-WLS-001-M' },
      { size: 'L', color: 'White', colorHex: '#FFFFFF', stock: 45, sku: 'UT-WLS-001-L' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p3',
    name: "Vintage Indigo Denim Trucker Jacket",
    slug: 'vintage-indigo-denim-trucker-jacket',
    brand: 'UrbanThreads',
    category: 'Denim',
    categorySlug: 'denim',
    vendor: VENDORS[0]!,
    description: "Rugged yet styled denim jacket in authentic indigo wash. Heavyweight premium denim with metal buttons.",
    longDescription: "Rugged yet styled denim jacket in authentic indigo wash. Heavyweight premium denim with metal buttons. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=800"],
    basePrice: 3499,
    rating: 4.9,
    reviewCount: 212,
    soldCount: 44,
    gender: 'men',
    tags: ["denim", "jacket", "men", "outerwear"],
    material: '100% Cotton Denim',
    careInstructions: 'Machine wash cold inside out.',
    variants: [
      { size: 'S', color: 'Navy', colorHex: '#000080', stock: 15, sku: 'UT-MDJ-001-S' },
      { size: 'M', color: 'Navy', colorHex: '#000080', stock: 25, sku: 'UT-MDJ-001-M' },
      { size: 'L', color: 'Navy', colorHex: '#000080', stock: 30, sku: 'UT-MDJ-001-L' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p4',
    name: "Handcrafted Tan Leather Loafers",
    slug: 'handcrafted-tan-leather-loafers',
    brand: 'SoleMate',
    category: 'Footwear',
    categorySlug: 'footwear',
    vendor: VENDORS[2]!,
    description: "Handcrafted loafers in genuine tan leather with cushioned insoles and durable rubber outsoles.",
    longDescription: "Handcrafted loafers in genuine tan leather with cushioned insoles and durable rubber outsoles. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800"],
    basePrice: 3299,
    rating: 4.6,
    reviewCount: 78,
    soldCount: 51,
    gender: 'men',
    tags: ["shoes", "loafers", "men", "leather"],
    material: 'Premium Full Grain Leather',
    careInstructions: 'Wipe clean. Apply shoe cream.',
    variants: [
      { size: '41', color: 'Tan', colorHex: '#D2B48C', stock: 15, sku: 'SM-TLL-001-41' },
      { size: '42', color: 'Tan', colorHex: '#D2B48C', stock: 20, sku: 'SM-TLL-001-42' },
      { size: '43', color: 'Tan', colorHex: '#D2B48C', stock: 15, sku: 'SM-TLL-001-43' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p5',
    name: "Dupion Silk Nehru Jacket",
    slug: 'dupion-silk-nehru-jacket',
    brand: 'DesiCouture',
    category: 'Ethnic Wear',
    categorySlug: 'ethnic',
    vendor: VENDORS[1]!,
    description: "Elegant Nehru jacket in textured dupion silk. Features a mandarin collar and classic pocket square detailing.",
    longDescription: "Elegant Nehru jacket in textured dupion silk. Features a mandarin collar and classic pocket square detailing. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1614251056818-9d1e71a685bb?w=800"],
    basePrice: 2999,
    rating: 4.7,
    reviewCount: 83,
    soldCount: 58,
    gender: 'men',
    tags: ["ethnic", "nehru-jacket", "men", "festive"],
    material: 'Dupion Silk',
    careInstructions: 'Dry clean only.',
    variants: [
      { size: 'S', color: 'Rose Gold', image: '/images/products/crimson-lehenga-choli-set-2.png', colorHex: '#B76E79', stock: 20, sku: 'DC-MNJ-001-S' },
      { size: 'M', color: 'Rose Gold', image: '/images/products/crimson-lehenga-choli-set-2.png', colorHex: '#B76E79', stock: 25, sku: 'DC-MNJ-001-M' },
      { size: 'L', color: 'Rose Gold', image: '/images/products/crimson-lehenga-choli-set-2.png', colorHex: '#B76E79', stock: 20, sku: 'DC-MNJ-001-L' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p6',
    name: "Active Stretch Slim Fit Jeans",
    slug: 'active-stretch-slim-fit-jeans',
    brand: 'UrbanThreads',
    category: 'Denim',
    categorySlug: 'denim',
    vendor: VENDORS[0]!,
    description: "Modern slim fit denim in dark charcoal wash. Built with active stretch comfort technology.",
    longDescription: "Modern slim fit denim in dark charcoal wash. Built with active stretch comfort technology. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800"],
    basePrice: 2499,
    rating: 4.5,
    reviewCount: 65,
    soldCount: 65,
    gender: 'men',
    tags: ["denim", "jeans", "men", "casual"],
    material: '98% Cotton, 2% Elastane',
    careInstructions: 'Machine wash cold inside out.',
    variants: [
      { size: '32', color: 'Black', colorHex: '#1A1A1A', stock: 30, sku: 'UT-SFJ-001-32' },
      { size: '34', color: 'Black', colorHex: '#1A1A1A', stock: 40, sku: 'UT-SFJ-001-34' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 'p7',
    name: "Organic Cotton Crewneck Tee",
    slug: 'organic-cotton-crewneck-tee',
    brand: 'UrbanThreads',
    category: 'Tops',
    categorySlug: 'tops',
    vendor: VENDORS[0]!,
    description: "Ultra-soft organic cotton t-shirt. The perfect base layer for any casual outfit.",
    longDescription: "Ultra-soft organic cotton t-shirt. The perfect base layer for any casual outfit. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800"],
    basePrice: 999,
    rating: 4.7,
    reviewCount: 142,
    soldCount: 72,
    gender: 'men',
    tags: ["top", "tee", "men", "basics"],
    material: '100% Organic Cotton',
    careInstructions: 'Machine wash warm, tumble dry low.',
    variants: [
      { size: 'S', color: 'Black', colorHex: '#1A1A1A', stock: 50, sku: 'UT-BCT-001-S' },
      { size: 'M', color: 'Black', colorHex: '#1A1A1A', stock: 60, sku: 'UT-BCT-001-M' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p8',
    name: "Italian Suede Chelsea Boots",
    slug: 'italian-suede-chelsea-boots',
    brand: 'SoleMate',
    category: 'Footwear',
    categorySlug: 'footwear',
    vendor: VENDORS[2]!,
    description: "Heritage style chelsea boots in luxury Italian suede with elasticated side panels.",
    longDescription: "Heritage style chelsea boots in luxury Italian suede with elasticated side panels. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800"],
    basePrice: 4999,
    rating: 4.8,
    reviewCount: 57,
    soldCount: 79,
    gender: 'men',
    tags: ["shoes", "boots", "men", "suede"],
    material: 'Italian Suede Leather',
    careInstructions: 'Use suede protector spray before wearing.',
    variants: [
      { size: '41', color: 'Brown', colorHex: '#8B4513', stock: 10, sku: 'SM-BCB-001-41' },
      { size: '42', color: 'Brown', colorHex: '#8B4513', stock: 15, sku: 'SM-BCB-001-42' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p9',
    name: "Urban Utility Cargo Joggers",
    slug: 'urban-utility-cargo-joggers',
    brand: 'UrbanThreads',
    category: 'Denim',
    categorySlug: 'denim',
    vendor: VENDORS[0]!,
    description: "Relaxed cargo pants with elastic cuffs and multiple utility pockets. Styled for urban exploration.",
    longDescription: "Relaxed cargo pants with elastic cuffs and multiple utility pockets. Styled for urban exploration. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=800"],
    basePrice: 2799,
    rating: 4.4,
    reviewCount: 89,
    soldCount: 86,
    gender: 'men',
    tags: ["denim", "cargo", "men", "streetwear"],
    material: '100% Cotton Twill',
    careInstructions: 'Machine wash cold with similar colors.',
    variants: [
      { size: 'M', color: 'Camel', colorHex: '#C19A6B', stock: 20, sku: 'UT-KCJ-001-M' },
      { size: 'L', color: 'Camel', colorHex: '#C19A6B', stock: 25, sku: 'UT-KCJ-001-L' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p10',
    name: "Heavyweight Canvas Utility Overshirt",
    slug: 'heavyweight-canvas-utility-overshirt',
    brand: 'UrbanThreads',
    category: 'Shirts',
    categorySlug: 'shirts',
    vendor: VENDORS[0]!,
    description: "Rugged shirt-jacket with double chest pockets and heavy-duty button closures. Versatile seasonal layering.",
    longDescription: "Rugged shirt-jacket with double chest pockets and heavy-duty button closures. Versatile seasonal layering. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800"],
    basePrice: 2399,
    rating: 4.6,
    reviewCount: 110,
    soldCount: 93,
    gender: 'men',
    tags: ["shirt", "overshirt", "men", "layering"],
    material: '100% Heavy Cotton Canvas',
    careInstructions: 'Machine wash warm. Tumble dry medium.',
    variants: [
      { size: 'M', color: 'Olive', colorHex: '#808000', stock: 15, sku: 'UT-OGO-001-M' },
      { size: 'L', color: 'Olive', colorHex: '#808000', stock: 20, sku: 'UT-OGO-001-L' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p11',
    name: "Zari Embroidered Anarkali Kurta",
    slug: 'zari-embroidered-anarkali-kurta',
    brand: 'DesiCouture',
    category: 'Ethnic Wear',
    categorySlug: 'ethnic',
    vendor: VENDORS[1]!,
    description: "A timeless ivory anarkali with delicate hand-embroidery in gold thread. Paired with a churidar and dupatta.",
    longDescription: "A timeless ivory anarkali with delicate hand-embroidery in gold thread. Paired with a churidar and dupatta. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800", "https://images.unsplash.com/photo-1614251056798-0a63eda2bb25?w=800"],
    basePrice: 3499,
    rating: 4.9,
    reviewCount: 482,
    soldCount: 100,
    gender: 'women',
    tags: ["ethnic", "anarkali", "wedding"],
    material: '80% Pure Cotton, 20% Silk Blend',
    careInstructions: 'Dry clean only. Store in a muslin bag.',
    variants: [
      { size: 'S', color: 'Ivory', image: '/images/products/ivory_anarkali.png', colorHex: '#FFFFF0', stock: 15, sku: 'DC-EAK-001-S' },
      { size: 'M', color: 'Ivory', image: '/images/products/ivory_anarkali.png', colorHex: '#FFFFF0', stock: 20, sku: 'DC-EAK-001-M' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p12',
    name: "Crimson Banarasi Lehenga Choli",
    slug: 'crimson-banarasi-lehenga-choli',
    brand: 'DesiCouture',
    category: 'Ethnic Wear',
    categorySlug: 'ethnic',
    vendor: VENDORS[1]!,
    description: "Bridal-grade crimson lehenga with zari embroidery and matching blouse. Perfect for weddings and receptions.",
    longDescription: "Bridal-grade crimson lehenga with zari embroidery and matching blouse. Perfect for weddings and receptions. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800", "https://images.unsplash.com/photo-1591093803775-fc1b9c4fa61b?w=800"],
    basePrice: 12999,
    rating: 4.8,
    reviewCount: 134,
    soldCount: 107,
    gender: 'women',
    tags: ["bridal", "lehenga", "wedding"],
    material: 'Banarasi Silk, Velvet Border',
    careInstructions: 'Dry clean only.',
    variants: [
      { size: 'S', color: 'Crimson Red', image: '/images/products/crimson-banarasi-lehenga-choli.png', colorHex: '#DC2626', stock: 5, sku: 'DC-CLC-001-S' },
      { size: 'M', color: 'Crimson Red', image: '/images/products/crimson-banarasi-lehenga-choli.png', colorHex: '#DC2626', stock: 8, sku: 'DC-CLC-001-M' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p13',
    name: "Georgette Bandhani Saree",
    slug: 'georgette-bandhani-saree',
    brand: 'DesiCouture',
    category: 'Ethnic Wear',
    categorySlug: 'ethnic',
    vendor: VENDORS[1]!,
    description: "Hand-tied bandhani saree in rich teal with golden zari border. Includes an unstitched blouse piece.",
    longDescription: "Hand-tied bandhani saree in rich teal with golden zari border. Includes an unstitched blouse piece. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1617627143233-f95b7fce1b3f?w=800"],
    basePrice: 4999,
    rating: 4.6,
    reviewCount: 87,
    soldCount: 114,
    gender: 'women',
    tags: ["saree", "bandhani", "ethnic"],
    material: 'Pure Georgette',
    careInstructions: 'Hand wash only.',
    variants: [
      { size: 'Free Size', color: 'Bandhani Red', image: '/images/products/georgette-bandhani-saree.png', colorHex: '#C026D3', stock: 20, sku: 'DC-TBS-001-FS' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p14',
    name: "Flutter Sleeve Floral Maxi Dress",
    slug: 'flutter-sleeve-floral-maxi-dress',
    brand: 'UrbanThreads',
    category: 'Dresses',
    categorySlug: 'dresses',
    vendor: VENDORS[0]!,
    description: "Floor-length maxi in midnight navy with delicate floral print. Features a flutter sleeve and ruched waist.",
    longDescription: "Floor-length maxi in midnight navy with delicate floral print. Features a flutter sleeve and ruched waist. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800"],
    basePrice: 2899,
    rating: 4.8,
    reviewCount: 234,
    soldCount: 121,
    gender: 'women',
    tags: ["maxi", "floral", "dress"],
    material: 'Viscose Rayon',
    careInstructions: 'Machine wash gentle. Tumble dry low.',
    variants: [
      { size: 'S', color: 'Floral Red', colorHex: '#E11D48', stock: 18, sku: 'UT-MFD-001-S' },
      { size: 'M', color: 'Floral Red', colorHex: '#E11D48', stock: 22, sku: 'UT-MFD-001-M' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p15',
    name: "Blush Cowl Neck Satin Slip Dress",
    slug: 'blush-cowl-neck-satin-slip-dress',
    brand: 'UrbanThreads',
    category: 'Dresses',
    categorySlug: 'dresses',
    vendor: VENDORS[0]!,
    description: "Elegant satin slip dress in blush with adjustable spaghetti straps. Perfect for date nights.",
    longDescription: "Elegant satin slip dress in blush with adjustable spaghetti straps. Perfect for date nights. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800"],
    basePrice: 1999,
    rating: 4.6,
    reviewCount: 189,
    soldCount: 128,
    gender: 'women',
    tags: ["dress", "satin", "evening"],
    material: '100% Satin',
    careInstructions: 'Hand wash cold.',
    variants: [
      { size: 'S', color: 'Blush', colorHex: '#DE5D83', stock: 15, sku: 'UT-BSD-001-S' },
      { size: 'M', color: 'Blush', colorHex: '#DE5D83', stock: 20, sku: 'UT-BSD-001-M' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p16',
    name: "Oversized Pure Linen Shirt",
    slug: 'oversized-pure-linen-shirt',
    brand: 'VelveteenRose',
    category: 'Shirts',
    categorySlug: 'shirts',
    vendor: VENDORS[4]!,
    description: "Oversized linen shirt in sage green. Wear open as a jacket or buttoned up. Versatile wardrobe essential.",
    longDescription: "Oversized linen shirt in sage green. Wear open as a jacket or buttoned up. Versatile wardrobe essential. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1533659124865-d6072dc035e1?w=800"],
    basePrice: 1799,
    rating: 4.7,
    reviewCount: 203,
    soldCount: 135,
    gender: 'women',
    tags: ["top", "linen", "shirt", "versatile"],
    material: '100% Linen',
    careInstructions: 'Machine wash cold.',
    variants: [
      { size: 'S', color: 'White', colorHex: '#FFFFFF', stock: 25, sku: 'VR-SGL-001-S' },
      { size: 'M', color: 'White', colorHex: '#FFFFFF', stock: 30, sku: 'VR-SGL-001-M' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p17',
    name: "Classic High-Rise Straight Jeans",
    slug: 'classic-high-rise-straight-jeans',
    brand: 'UrbanThreads',
    category: 'Denim',
    categorySlug: 'denim',
    vendor: VENDORS[0]!,
    description: "Classic high-rise straight cut in authentic denim. Timeless, flattering silhouette.",
    longDescription: "Classic high-rise straight cut in authentic denim. Timeless, flattering silhouette. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800"],
    basePrice: 2299,
    rating: 4.8,
    reviewCount: 567,
    soldCount: 142,
    gender: 'women',
    tags: ["denim", "jeans", "classic"],
    material: '98% Cotton, 2% Elastane',
    careInstructions: 'Machine wash cold inside out.',
    variants: [
      { size: '28', color: 'Black', colorHex: '#1A1A1A', stock: 35, sku: 'UT-HSJ-001-28' },
      { size: '30', color: 'Black', colorHex: '#1A1A1A', stock: 40, sku: 'UT-HSJ-001-30' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p18',
    name: "Coastal Block Print Cotton Kaftan",
    slug: 'coastal-block-print-cotton-kaftan',
    brand: 'VelveteenRose',
    category: 'Kaftans',
    categorySlug: 'kaftans',
    vendor: VENDORS[4]!,
    description: "Vibrant block-print kaftan in lightweight cotton. Breezy beach cover-up or loungewear.",
    longDescription: "Vibrant block-print kaftan in lightweight cotton. Breezy beach cover-up or loungewear. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800"],
    basePrice: 2099,
    rating: 4.5,
    reviewCount: 167,
    soldCount: 149,
    gender: 'women',
    tags: ["kaftan", "resort", "boho"],
    material: '100% Cotton',
    careInstructions: 'Machine wash cold.',
    variants: [
      { size: 'Free Size', color: 'Orange', colorHex: '#FF7F50', stock: 40, sku: 'VR-BPK-001-FS' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 'p19',
    name: "Metallic Gold Strappy Heels",
    slug: 'metallic-gold-strappy-heels',
    brand: 'SoleMate',
    category: 'Footwear',
    categorySlug: 'footwear',
    vendor: VENDORS[2]!,
    description: "Handcrafted gold strappy block heels with ankle tie. 3-inch heel height, padded insole for all-day comfort.",
    longDescription: "Handcrafted gold strappy block heels with ankle tie. 3-inch heel height, padded insole for all-day comfort. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800"],
    basePrice: 2799,
    rating: 4.7,
    reviewCount: 198,
    soldCount: 156,
    gender: 'women',
    tags: ["heels", "gold", "party"],
    material: 'Metallic Leather Upper, Memory Foam Insole',
    careInstructions: 'Wipe clean with damp cloth.',
    variants: [
      { size: '37', color: 'Gold', colorHex: '#FFD700', stock: 15, sku: 'SM-GSB-001-37' },
      { size: '38', color: 'Gold', colorHex: '#FFD700', stock: 20, sku: 'SM-GSB-001-38' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p20',
    name: "Ribbed Knit Longline Co-ord Set",
    slug: 'ribbed-knit-longline-co-ord-set',
    brand: 'UrbanThreads',
    category: 'Co-ord Sets',
    categorySlug: 'coords',
    vendor: VENDORS[0]!,
    description: "Luxe ribbed knit co-ord in camel. Longline blazer + straight-leg trousers. The power suit reinvented.",
    longDescription: "Luxe ribbed knit co-ord in camel. Longline blazer + straight-leg trousers. The power suit reinvented. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800"],
    basePrice: 3999,
    rating: 4.9,
    reviewCount: 189,
    soldCount: 163,
    gender: 'women',
    tags: ["coord", "knit", "power suit"],
    material: '65% Acrylic, 35% Wool Blend',
    careInstructions: 'Dry clean only.',
    variants: [
      { size: 'S', color: 'Camel', colorHex: '#C19A6B', stock: 15, sku: 'UT-CRK-001-S' },
      { size: 'M', color: 'Camel', colorHex: '#C19A6B', stock: 20, sku: 'UT-CRK-001-M' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p21',
    name: "Geometric Pattern Cotton Kurta",
    slug: 'geometric-pattern-cotton-kurta',
    brand: 'DesiCouture',
    category: 'Ethnic Wear',
    categorySlug: 'ethnic',
    vendor: VENDORS[1]!,
    description: "Soft, breathable cotton kurta for boys with mini geometric print. Comfort fit for all festive wear.",
    longDescription: "Soft, breathable cotton kurta for boys with mini geometric print. Comfort fit for all festive wear. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1564463836146-4e30522c2984?w=800"],
    basePrice: 899,
    rating: 4.6,
    reviewCount: 42,
    soldCount: 170,
    gender: 'boys',
    tags: ["ethnic", "kurta", "boys", "cotton"],
    material: '100% Pure Cotton',
    careInstructions: 'Machine wash cold. Dry in shade.',
    variants: [
      { size: '4-5Y', color: 'Mustard', image: '/images/products/mustard_kurta.png', colorHex: '#FFDB58', stock: 25, sku: 'DC-BCK-001-45' },
      { size: '6-7Y', color: 'Mustard', image: '/images/products/mustard_kurta.png', colorHex: '#FFDB58', stock: 30, sku: 'DC-BCK-001-67' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p22',
    name: "Mandarin Collar Cotton Linen Shirt",
    slug: 'mandarin-collar-cotton-linen-shirt',
    brand: 'UrbanThreads',
    category: 'Shirts',
    categorySlug: 'shirts',
    vendor: VENDORS[0]!,
    description: "Smart linen shirt for boys with high mandarin collar. Light, airy, and styled for warm afternoons.",
    longDescription: "Smart linen shirt for boys with high mandarin collar. Light, airy, and styled for warm afternoons. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800"],
    basePrice: 1199,
    rating: 4.7,
    reviewCount: 54,
    soldCount: 177,
    gender: 'boys',
    tags: ["shirt", "linen", "boys", "smart-casual"],
    material: '60% Linen, 40% Cotton',
    careInstructions: 'Machine wash gentle. Warm iron.',
    variants: [
      { size: '6-7Y', color: 'White', colorHex: '#FFFFFF', stock: 20, sku: 'UT-BMC-001-67' },
      { size: '8-9Y', color: 'White', colorHex: '#FFFFFF', stock: 25, sku: 'UT-BMC-001-89' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p23',
    name: "Ripped Wash Denim Jacket",
    slug: 'ripped-wash-denim-jacket',
    brand: 'UrbanThreads',
    category: 'Denim',
    categorySlug: 'denim',
    vendor: VENDORS[0]!,
    description: "Cool and classic denim jacket with front button pockets. A must-have outer layer for dynamic boys.",
    longDescription: "Cool and classic denim jacket with front button pockets. A must-have outer layer for dynamic boys. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=800"],
    basePrice: 1899,
    rating: 4.8,
    reviewCount: 38,
    soldCount: 34,
    gender: 'boys',
    tags: ["denim", "jacket", "boys", "outerwear"],
    material: '100% Cotton Indigo Denim',
    careInstructions: 'Wash cold inside out. Color may bleed.',
    variants: [
      { size: '6-7Y', color: 'Navy', colorHex: '#000080', stock: 15, sku: 'UT-BDT-001-67' },
      { size: '8-9Y', color: 'Navy', colorHex: '#000080', stock: 20, sku: 'UT-BDT-001-89' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p24',
    name: "Artisan Leather Slip-On Shoes",
    slug: 'artisan-leather-slip-on-shoes',
    brand: 'SoleMate',
    category: 'Footwear',
    categorySlug: 'footwear',
    vendor: VENDORS[2]!,
    description: "Premium leather shoes with elastic side gussets for easy wear. Padded ankle cuff for soft support.",
    longDescription: "Premium leather shoes with elastic side gussets for easy wear. Padded ankle cuff for soft support. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800"],
    basePrice: 1599,
    rating: 4.5,
    reviewCount: 29,
    soldCount: 41,
    gender: 'boys',
    tags: ["shoes", "slip-ons", "boys", "leather"],
    material: 'Genuine Leather, Rubber Sole',
    careInstructions: 'Wipe with leather cleaner.',
    variants: [
      { size: '26', color: 'Tan', colorHex: '#D2B48C', stock: 15, sku: 'SM-BLS-001-26' },
      { size: '28', color: 'Tan', colorHex: '#D2B48C', stock: 18, sku: 'SM-BLS-001-28' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 'p25',
    name: "Three-Piece Silk Blend Ethnic Set",
    slug: 'three-piece-silk-blend-ethnic-set',
    brand: 'DesiCouture',
    category: 'Ethnic Wear',
    categorySlug: 'ethnic',
    vendor: VENDORS[1]!,
    description: "Three-piece outfit: Kurta, Pyjama, and contrast Nehru Jacket. Perfect for Diwali and family weddings.",
    longDescription: "Three-piece outfit: Kurta, Pyjama, and contrast Nehru Jacket. Perfect for Diwali and family weddings. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1614251056818-9d1e71a685bb?w=800"],
    basePrice: 2499,
    rating: 4.9,
    reviewCount: 68,
    soldCount: 48,
    gender: 'boys',
    tags: ["ethnic", "nehru-jacket", "boys", "festive"],
    material: 'Silk Blend',
    careInstructions: 'Dry clean only.',
    variants: [
      { size: '6-7Y', color: 'Rose Gold', image: '/images/products/crimson-lehenga-choli-set-2.png', colorHex: '#B76E79', stock: 15, sku: 'DC-BFN-001-67' },
      { size: '8-9Y', color: 'Rose Gold', image: '/images/products/crimson-lehenga-choli-set-2.png', colorHex: '#B76E79', stock: 20, sku: 'DC-BFN-001-89' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p26',
    name: "Casual Solid Crewneck Tee",
    slug: 'casual-solid-crewneck-tee',
    brand: 'UrbanThreads',
    category: 'Tops',
    categorySlug: 'tops',
    vendor: VENDORS[0]!,
    description: "Everyday comfortable crewneck t-shirt in pure organic cotton. Soft and durable.",
    longDescription: "Everyday comfortable crewneck t-shirt in pure organic cotton. Soft and durable. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800"],
    basePrice: 699,
    rating: 4.7,
    reviewCount: 110,
    soldCount: 55,
    gender: 'boys',
    tags: ["top", "tee", "boys", "casual"],
    material: '100% Organic Cotton',
    careInstructions: 'Machine wash cold.',
    variants: [
      { size: '6-7Y', color: 'Black', colorHex: '#1A1A1A', stock: 35, sku: 'UT-BCC-001-67' },
      { size: '8-9Y', color: 'Black', colorHex: '#1A1A1A', stock: 40, sku: 'UT-BCC-001-89' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p27',
    name: "Relaxed Fit Ripped Denim Jeans",
    slug: 'relaxed-fit-ripped-denim-jeans',
    brand: 'UrbanThreads',
    category: 'Denim',
    categorySlug: 'denim',
    vendor: VENDORS[0]!,
    description: "Trendy ripped details in a relaxed straight-leg denim. Adjustable internal waist band.",
    longDescription: "Trendy ripped details in a relaxed straight-leg denim. Adjustable internal waist band. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=800"],
    basePrice: 1499,
    rating: 4.6,
    reviewCount: 45,
    soldCount: 62,
    gender: 'boys',
    tags: ["denim", "jeans", "boys", "trendy"],
    material: '98% Cotton, 2% Spandex',
    careInstructions: 'Machine wash warm inside out.',
    variants: [
      { size: '8-9Y', color: 'Navy', colorHex: '#000080', stock: 20, sku: 'UT-BRD-001-89' },
      { size: '10-12Y', color: 'Navy', colorHex: '#000080', stock: 25, sku: 'UT-BRD-001-10' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p28',
    name: "Vulcanized Canvas Sneakers",
    slug: 'vulcanized-canvas-sneakers',
    brand: 'SoleMate',
    category: 'Footwear',
    categorySlug: 'footwear',
    vendor: VENDORS[2]!,
    description: "Lace-up sneakers in durable canvas with dual-density rubber toe cap for playgrounds.",
    longDescription: "Lace-up sneakers in durable canvas with dual-density rubber toe cap for playgrounds. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800"],
    basePrice: 1099,
    rating: 4.5,
    reviewCount: 63,
    soldCount: 69,
    gender: 'boys',
    tags: ["shoes", "sneakers", "boys", "canvas"],
    material: 'Canvas Upper, Vulcanized Sole',
    careInstructions: 'Hand wash. Air dry.',
    variants: [
      { size: '30', color: 'Navy', colorHex: '#000080', stock: 30, sku: 'SM-BCC-001-30' },
      { size: '32', color: 'Navy', colorHex: '#000080', stock: 35, sku: 'SM-BCC-001-32' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 'p29',
    name: "Twill Utility Cargo Shorts",
    slug: 'twill-utility-cargo-shorts',
    brand: 'UrbanThreads',
    category: 'Denim',
    categorySlug: 'denim',
    vendor: VENDORS[0]!,
    description: "Adventure-ready cargo shorts with utility flap pockets. Soft elastic waist loops.",
    longDescription: "Adventure-ready cargo shorts with utility flap pockets. Soft elastic waist loops. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=800"],
    basePrice: 999,
    rating: 4.4,
    reviewCount: 31,
    soldCount: 76,
    gender: 'boys',
    tags: ["denim", "shorts", "boys", "cargo"],
    material: '100% Cotton Cargo Twill',
    careInstructions: 'Machine wash cold.',
    variants: [
      { size: '4-5Y', color: 'Camel', colorHex: '#C19A6B', stock: 20, sku: 'UT-BCS-001-45' },
      { size: '6-7Y', color: 'Camel', colorHex: '#C19A6B', stock: 25, sku: 'UT-BCS-001-67' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p30',
    name: "Classic Striped Piqu\u00e9 Polo",
    slug: 'classic-striped-pique-polo',
    brand: 'UrbanThreads',
    category: 'Tops',
    categorySlug: 'tops',
    vendor: VENDORS[0]!,
    description: "Classic cotton piqu\u00e9 polo with athletic stripes. Embroidered crest detail on chest.",
    longDescription: "Classic cotton piqu\u00e9 polo with athletic stripes. Embroidered crest detail on chest. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1625910513413-89803153d36b?w=800"],
    basePrice: 899,
    rating: 4.6,
    reviewCount: 52,
    soldCount: 83,
    gender: 'boys',
    tags: ["top", "polo", "boys", "sporty"],
    material: '100% Cotton Piqué',
    careInstructions: 'Machine wash gentle. Flat dry.',
    variants: [
      { size: '6-7Y', color: 'Navy', colorHex: '#000080', stock: 20, sku: 'UT-BSP-001-67' },
      { size: '8-9Y', color: 'Navy', colorHex: '#000080', stock: 25, sku: 'UT-BSP-001-89' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p31',
    name: "Floral Zari Net Lehenga Choli",
    slug: 'floral-zari-net-lehenga-choli',
    brand: 'DesiCouture',
    category: 'Ethnic Wear',
    categorySlug: 'ethnic',
    vendor: VENDORS[1]!,
    description: "Charming girls lehenga set with floral thread work and net dupatta. Breathable lining inside.",
    longDescription: "Charming girls lehenga set with floral thread work and net dupatta. Breathable lining inside. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800"],
    basePrice: 1999,
    rating: 4.8,
    reviewCount: 53,
    soldCount: 90,
    gender: 'girls',
    tags: ["ethnic", "lehenga", "girls", "festive"],
    material: 'Georgette Silk, Cotton Lining',
    careInstructions: 'Dry clean recommended.',
    variants: [
      { size: '4-5Y', color: 'Rose Gold', image: '/images/products/crimson-lehenga-choli-set-2.png', colorHex: '#B76E79', stock: 15, sku: 'DC-GEL-001-45' },
      { size: '6-7Y', color: 'Rose Gold', image: '/images/products/crimson-lehenga-choli-set-2.png', colorHex: '#B76E79', stock: 20, sku: 'DC-GEL-001-67' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p32',
    name: "Tiered Garden Floral Cotton Frock",
    slug: 'tiered-garden-floral-cotton-frock',
    brand: 'UrbanThreads',
    category: 'Dresses',
    categorySlug: 'dresses',
    vendor: VENDORS[0]!,
    description: "Frock dress with flared tiered hem and tie-up back sash. Covered in hand-printed garden florals.",
    longDescription: "Frock dress with flared tiered hem and tie-up back sash. Covered in hand-printed garden florals. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800"],
    basePrice: 1299,
    rating: 4.7,
    reviewCount: 74,
    soldCount: 97,
    gender: 'girls',
    tags: ["dress", "floral", "girls", "party"],
    material: '100% Muslin Cotton',
    careInstructions: 'Hand wash cold. Dry in shade.',
    variants: [
      { size: '6-7Y', color: 'Blush', colorHex: '#DE5D83', stock: 20, sku: 'UT-GFP-001-67' },
      { size: '8-9Y', color: 'Blush', colorHex: '#DE5D83', stock: 25, sku: 'UT-GFP-001-89' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p33',
    name: "Classic Overall Denim Pinafore",
    slug: 'classic-overall-denim-pinafore',
    brand: 'UrbanThreads',
    category: 'Denim',
    categorySlug: 'denim',
    vendor: VENDORS[0]!,
    description: "Classic overall dress in soft pre-washed denim. Adjustable metal slides on straps.",
    longDescription: "Classic overall dress in soft pre-washed denim. Adjustable metal slides on straps. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800"],
    basePrice: 1499,
    rating: 4.6,
    reviewCount: 29,
    soldCount: 104,
    gender: 'girls',
    tags: ["denim", "dress", "girls", "casual"],
    material: '98% Cotton Denim, 2% Lycra',
    careInstructions: 'Machine wash cold.',
    variants: [
      { size: '6-7Y', color: 'Black', colorHex: '#1A1A1A', stock: 15, sku: 'UT-GDP-001-67' },
      { size: '8-9Y', color: 'Black', colorHex: '#1A1A1A', stock: 20, sku: 'UT-GDP-001-89' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p34',
    name: "Vegan Leather Mary Jane Flats",
    slug: 'vegan-leather-mary-jane-flats',
    brand: 'SoleMate',
    category: 'Footwear',
    categorySlug: 'footwear',
    vendor: VENDORS[2]!,
    description: "Charming flat shoes with secure hook-and-loop strap. Accent bow detailing on front toe.",
    longDescription: "Charming flat shoes with secure hook-and-loop strap. Accent bow detailing on front toe. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=800"],
    basePrice: 1199,
    rating: 4.5,
    reviewCount: 46,
    soldCount: 111,
    gender: 'girls',
    tags: ["shoes", "flats", "girls", "casual"],
    material: 'Soft Vegan Leather, Flexible Sole',
    careInstructions: 'Wipe clean.',
    variants: [
      { size: '26', color: 'Blush', colorHex: '#DE5D83', stock: 20, sku: 'SM-GMJ-001-26' },
      { size: '28', color: 'Blush', colorHex: '#DE5D83', stock: 25, sku: 'SM-GMJ-001-28' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 'p35',
    name: "Sharara Pants & Block Print Kurti Set",
    slug: 'sharara-pants-and-block-print-kurti-set',
    brand: 'DesiCouture',
    category: 'Ethnic Wear',
    categorySlug: 'ethnic',
    vendor: VENDORS[1]!,
    description: "Traditional Jaipur block-print short kurti with flared sharara pants. Bright, light, and comfortable.",
    longDescription: "Traditional Jaipur block-print short kurti with flared sharara pants. Bright, light, and comfortable. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1564463836146-4e30522c2984?w=800"],
    basePrice: 1599,
    rating: 4.7,
    reviewCount: 39,
    soldCount: 118,
    gender: 'girls',
    tags: ["ethnic", "kurta", "girls", "cotton"],
    material: '100% Jaipur Cotton',
    careInstructions: 'Wash separately in cold water.',
    variants: [
      { size: '6-7Y', color: 'Mustard', image: '/images/products/mustard_kurta.png', colorHex: '#FFDB58', stock: 15, sku: 'DC-GBP-001-67' },
      { size: '8-9Y', color: 'Mustard', image: '/images/products/mustard_kurta.png', colorHex: '#FFDB58', stock: 20, sku: 'DC-GBP-001-89' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p36',
    name: "Ruffled Cap Sleeve Linen Top",
    slug: 'ruffled-cap-sleeve-linen-top',
    brand: 'VelveteenRose',
    category: 'Tops',
    categorySlug: 'tops',
    vendor: VENDORS[4]!,
    description: "Breezy linen-blend top featuring dual layered ruffles on cap sleeves. Styled for sunny days.",
    longDescription: "Breezy linen-blend top featuring dual layered ruffles on cap sleeves. Styled for sunny days. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1533659124865-d6072dc035e1?w=800"],
    basePrice: 799,
    rating: 4.4,
    reviewCount: 31,
    soldCount: 125,
    gender: 'girls',
    tags: ["top", "ruffles", "girls", "summer"],
    material: '70% Cotton, 30% Linen',
    careInstructions: 'Machine wash warm.',
    variants: [
      { size: '6-7Y', color: 'White', colorHex: '#FFFFFF', stock: 20, sku: 'VR-GRS-001-67' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 'p37',
    name: "Glitter Mesh Ballerina Flats",
    slug: 'glitter-mesh-ballerina-flats',
    brand: 'SoleMate',
    category: 'Footwear',
    categorySlug: 'footwear',
    vendor: VENDORS[2]!,
    description: "Party-perfect ballerina flats covered in subtle glitter mesh. Non-slip outsole.",
    longDescription: "Party-perfect ballerina flats covered in subtle glitter mesh. Non-slip outsole. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1560343776-97e7d202ff0e?w=800"],
    basePrice: 1399,
    rating: 4.6,
    reviewCount: 52,
    soldCount: 132,
    gender: 'girls',
    tags: ["shoes", "flats", "girls", "glitter"],
    material: 'Glitter Mesh Upper, Synthetic Sole',
    careInstructions: 'Gently wipe with dry brush.',
    variants: [
      { size: '28', color: 'Silver', colorHex: '#C0C0C0', stock: 20, sku: 'SM-GGB-001-28' },
      { size: '30', color: 'Silver', colorHex: '#C0C0C0', stock: 25, sku: 'SM-GGB-001-30' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p38',
    name: "Coral Strappy Tiered Sundress",
    slug: 'coral-strappy-tiered-sundress',
    brand: 'UrbanThreads',
    category: 'Dresses',
    categorySlug: 'dresses',
    vendor: VENDORS[0]!,
    description: "Fluid tiered skirt dress in bright coral with easy spaghetti shoulder ties.",
    longDescription: "Fluid tiered skirt dress in bright coral with easy spaghetti shoulder ties. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800"],
    basePrice: 1199,
    rating: 4.5,
    reviewCount: 41,
    soldCount: 139,
    gender: 'girls',
    tags: ["dress", "sundress", "girls", "vacation"],
    material: 'Rayon Challis',
    careInstructions: 'Machine wash gentle. Tumble dry low.',
    variants: [
      { size: '6-7Y', color: 'Orange', colorHex: '#FF7F50', stock: 18, sku: 'UT-GTS-001-67' },
      { size: '8-9Y', color: 'Orange', colorHex: '#FF7F50', stock: 22, sku: 'UT-GTS-001-89' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p39',
    name: "Embroidered Frayed Denim Shorts",
    slug: 'embroidered-frayed-denim-shorts',
    brand: 'UrbanThreads',
    category: 'Denim',
    categorySlug: 'denim',
    vendor: VENDORS[0]!,
    description: "Soft denim shorts with frayed edges and cute embroidery motifs on front pockets.",
    longDescription: "Soft denim shorts with frayed edges and cute embroidery motifs on front pockets. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=800"],
    basePrice: 899,
    rating: 4.5,
    reviewCount: 22,
    soldCount: 146,
    gender: 'girls',
    tags: ["denim", "shorts", "girls", "embroidered"],
    material: '99% Cotton, 1% Spandex',
    careInstructions: 'Machine wash cold.',
    variants: [
      { size: '6-7Y', color: 'Navy', colorHex: '#000080', stock: 25, sku: 'UT-GDS-001-67' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 'p40',
    name: "Pointelle Knit Pastel Cardigan",
    slug: 'pointelle-knit-pastel-cardigan',
    brand: 'UrbanThreads',
    category: 'Tops',
    categorySlug: 'tops',
    vendor: VENDORS[0]!,
    description: "Cozy pointelle knit cardigan in sweet pastel pink. Contrast wood-look buttons.",
    longDescription: "Cozy pointelle knit cardigan in sweet pastel pink. Contrast wood-look buttons. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1533659124865-d6072dc035e1?w=800"],
    basePrice: 1399,
    rating: 4.8,
    reviewCount: 56,
    soldCount: 153,
    gender: 'girls',
    tags: ["top", "cardigan", "girls", "knitwear"],
    material: '100% Fine Acrylic Yarn',
    careInstructions: 'Hand wash warm. Lay flat to dry.',
    variants: [
      { size: '6-7Y', color: 'Blush', colorHex: '#DE5D83', stock: 15, sku: 'UT-GPK-001-67' },
      { size: '8-9Y', color: 'Blush', colorHex: '#DE5D83', stock: 20, sku: 'UT-GPK-001-89' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p41',
    name: "Full-Grain Leather Belt",
    slug: 'full-grain-leather-belt',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Genuine full-grain leather belt with solid brass buckle. Brushed hardware finish.",
    longDescription: "Genuine full-grain leather belt with solid brass buckle. Brushed hardware finish. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800"],
    basePrice: 1299,
    rating: 4.8,
    reviewCount: 97,
    soldCount: 160,
    gender: 'men',
    tags: ["accessories", "belt", "men", "leather"],
    material: 'Full-Grain Leather',
    careInstructions: 'Clean with dry cloth. Apply leather lotion.',
    variants: [
      { size: 'Free Size', color: 'Brown', colorHex: '#8B4513', stock: 45, sku: 'GC-BLT-001' },
      { size: 'Free Size', color: 'Black', colorHex: '#1A1A1A', stock: 40, sku: 'GC-BLT-002' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p42',
    name: "RFID Blocking Leather Cardholder",
    slug: 'rfid-blocking-leather-cardholder',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Sleek wallet cardholder with 4 card slots and central cash sleeve. RFID blocking design.",
    longDescription: "Sleek wallet cardholder with 4 card slots and central cash sleeve. RFID blocking design. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1606503830058-c39242c38865?w=800"],
    basePrice: 899,
    rating: 4.7,
    reviewCount: 112,
    soldCount: 167,
    gender: 'men',
    tags: ["accessories", "wallet", "men", "minimal"],
    material: 'Vegetable Tanned Leather',
    careInstructions: 'Wipe with soft damp cloth.',
    variants: [
      { size: 'Free Size', color: 'Tan', colorHex: '#D2B48C', stock: 80, sku: 'GC-WLT-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p43',
    name: "Stainless Steel Chronograph Watch",
    slug: 'stainless-steel-chronograph-watch',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Premium quartz chronograph watch in polished stainless steel case and link bracelet.",
    longDescription: "Premium quartz chronograph watch in polished stainless steel case and link bracelet. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1627123424574-724758594e93?w=800"],
    basePrice: 5999,
    rating: 4.9,
    reviewCount: 54,
    soldCount: 174,
    gender: 'men',
    tags: ["accessories", "watch", "men", "formal"],
    material: 'Stainless Steel Case, Hardened Mineral Glass',
    careInstructions: 'Water resistant to 50m. Wipe clean.',
    variants: [
      { size: 'Free Size', color: 'Silver/Black', colorHex: '#C0C0C0', stock: 25, sku: 'GC-WCH-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p44',
    name: "Polarized Aviator Sunglasses",
    slug: 'polarized-aviator-sunglasses',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Iconic aviator frame sunglasses with polarized lenses. 100% UVA/UVB protection.",
    longDescription: "Iconic aviator frame sunglasses with polarized lenses. 100% UVA/UVB protection. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800"],
    basePrice: 1499,
    rating: 4.6,
    reviewCount: 88,
    soldCount: 31,
    gender: 'men',
    tags: ["accessories", "eyewear", "men", "summer"],
    material: 'Metal Alloy Frame, Polycarbonate Lenses',
    careInstructions: 'Clean lenses with microfiber cloth.',
    variants: [
      { size: 'Free Size', color: 'Gold/Green', colorHex: '#FFD700', stock: 65, sku: 'GC-SUN-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p45',
    name: "Woven Kashmiri Wool Scarf",
    slug: 'woven-kashmiri-wool-scarf',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Warm and luxurious wool muffler, woven by artisans in Kashmir with fine fringed ends.",
    longDescription: "Warm and luxurious wool muffler, woven by artisans in Kashmir with fine fringed ends. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800"],
    basePrice: 1899,
    rating: 4.7,
    reviewCount: 39,
    soldCount: 38,
    gender: 'men',
    tags: ["accessories", "scarf", "men", "winter"],
    material: '100% Kashmiri Wool',
    careInstructions: 'Dry clean recommended.',
    variants: [
      { size: 'Free Size', color: 'Charcoal', colorHex: '#1A1A1A', stock: 30, sku: 'GC-MFL-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 'p46',
    name: "Gold Filigree Statement Earrings",
    slug: 'gold-filigree-statement-earrings',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Handcrafted gold filigree drop earrings inspired by Chettinad jewellery. Lightweight, hypoallergenic.",
    longDescription: "Handcrafted gold filigree drop earrings inspired by Chettinad jewellery. Lightweight, hypoallergenic. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800"],
    basePrice: 1999,
    rating: 4.9,
    reviewCount: 312,
    soldCount: 45,
    gender: 'women',
    tags: ["jewellery", "earrings", "ethnic"],
    material: '22K Gold Plated Brass, Hypoallergenic Posts',
    careInstructions: 'Store in the provided pouch. Avoid perfume.',
    variants: [
      { size: 'Free Size', color: 'Gold', colorHex: '#FFD700', stock: 80, sku: 'GC-EAR-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p47',
    name: "Structured Full-Grain Leather Tote",
    slug: 'structured-full-grain-leather-tote',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Full-grain leather structured tote in tan. Magnetic snap closure, internal zip pocket, laptop sleeve.",
    longDescription: "Full-grain leather structured tote in tan. Magnetic snap closure, internal zip pocket, laptop sleeve. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800"],
    basePrice: 5499,
    rating: 4.8,
    reviewCount: 178,
    soldCount: 52,
    gender: 'women',
    tags: ["bag", "tote", "leather", "office"],
    material: 'Full-Grain Leather, Suede Lining',
    careInstructions: 'Condition with leather cream. Avoid water.',
    variants: [
      { size: 'Free Size', color: 'Tan', colorHex: '#D2B48C', stock: 30, sku: 'GC-BAG-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 'p48',
    name: "Hand-Painted Silk Paisley Stole",
    slug: 'hand-painted-silk-paisley-stole',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Hand-painted silk stole in paisley motif. Wearable art \u2014 as a scarf, dupatta, or beach sarong.",
    longDescription: "Hand-painted silk stole in paisley motif. Wearable art \u2014 as a scarf, dupatta, or beach sarong. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800"],
    basePrice: 2499,
    rating: 4.7,
    reviewCount: 89,
    soldCount: 59,
    gender: 'women',
    tags: ["scarf", "silk", "accessories"],
    material: '100% Pure Silk',
    careInstructions: 'Dry clean only.',
    variants: [
      { size: 'Free Size', color: 'Ivory/Gold', colorHex: '#FFFFF0', stock: 50, sku: 'GC-SCF-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p49',
    name: "Embellished Beaded Minaudi\u00e8re Clutch",
    slug: 'embellished-beaded-minaudiere-clutch',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Embellished minaudi\u00e8re in antique gold with intricate bead work. Removable chain strap.",
    longDescription: "Embellished minaudi\u00e8re in antique gold with intricate bead work. Removable chain strap. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800"],
    basePrice: 3299,
    rating: 4.6,
    reviewCount: 67,
    soldCount: 66,
    gender: 'women',
    tags: ["bag", "clutch", "party", "evening"],
    material: 'Metal Frame, Beaded Exterior',
    careInstructions: 'Handle with care. Avoid moisture.',
    variants: [
      { size: 'Free Size', color: 'Antique Gold', colorHex: '#B8860B', stock: 20, sku: 'GC-CLT-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: false,
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p50',
    name: "Layered Pearl & Bead Choker",
    slug: 'layered-pearl-and-bead-choker',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Set of 3 layered bead chokers \u2014 miyuki beads, seed pearls and brass chain. Mix and match.",
    longDescription: "Set of 3 layered bead chokers \u2014 miyuki beads, seed pearls and brass chain. Mix and match. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800"],
    basePrice: 1499,
    rating: 4.5,
    reviewCount: 213,
    soldCount: 73,
    gender: 'women',
    tags: ["jewellery", "choker", "set"],
    material: 'Miyuki Beads, Freshwater Pearls, Brass Chain',
    careInstructions: 'Avoid water, perfume, sweat.',
    variants: [
      { size: 'Free Size', color: 'Blush/Pearl', colorHex: '#DE5D83', stock: 70, sku: 'GC-CHK-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p51',
    name: "Adjustable Satin Bow Tie",
    slug: 'adjustable-satin-bow-tie',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Charming pre-tied boys bow tie with adjustable neck strap. Perfect styling for family photography.",
    longDescription: "Charming pre-tied boys bow tie with adjustable neck strap. Perfect styling for family photography. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=800"],
    basePrice: 399,
    rating: 4.6,
    reviewCount: 18,
    soldCount: 80,
    gender: 'boys',
    tags: ["accessories", "bow-tie", "boys", "party"],
    material: 'Polyester Satin',
    careInstructions: 'Spot clean only.',
    variants: [
      { size: 'Free Size', color: 'Crimson Red', image: '/images/products/crimson-banarasi-lehenga-choli.png', colorHex: '#B7410E', stock: 50, sku: 'GC-BOW-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p52',
    name: "Flexible Rubber Frame Sunglasses",
    slug: 'flexible-rubber-frame-sunglasses',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Flexible rubber frame sunglasses for active boys. Drop-resistant, polarized, UV protection.",
    longDescription: "Flexible rubber frame sunglasses for active boys. Drop-resistant, polarized, UV protection. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800"],
    basePrice: 599,
    rating: 4.7,
    reviewCount: 33,
    soldCount: 87,
    gender: 'boys',
    tags: ["accessories", "eyewear", "boys", "rubber"],
    material: 'TPEE Flexible Rubber Frame',
    careInstructions: 'Wash under running water. Wipe dry.',
    variants: [
      { size: 'Free Size', color: 'Blue/Orange', colorHex: '#008080', stock: 90, sku: 'GC-SUN-002' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p53',
    name: "Rib-Knit Wool Beanie",
    slug: 'rib-knit-wool-beanie',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Thick knit beanie hat in stretchy rib stitch. Provides optimal warmth for boys during cold days.",
    longDescription: "Thick knit beanie hat in stretchy rib stitch. Provides optimal warmth for boys during cold days. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800"],
    basePrice: 499,
    rating: 4.5,
    reviewCount: 22,
    soldCount: 94,
    gender: 'boys',
    tags: ["accessories", "beanie", "boys", "winter"],
    material: 'Soft Acrylic Wool',
    careInstructions: 'Machine wash cold on gentle.',
    variants: [
      { size: 'Free Size', color: 'Mustard', image: '/images/products/mustard_kurta.png', colorHex: '#FFDB58', stock: 40, sku: 'GC-BEN-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 'p54',
    name: "Durable Canvas School Backpack",
    slug: 'durable-canvas-school-backpack',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Hardwearing canvas backpack with double zip compartments and side water bottle sleeves.",
    longDescription: "Hardwearing canvas backpack with double zip compartments and side water bottle sleeves. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800"],
    basePrice: 1299,
    rating: 4.8,
    reviewCount: 47,
    soldCount: 101,
    gender: 'boys',
    tags: ["accessories", "backpack", "boys", "school"],
    material: 'Waterproof Canvas, Nylon Lining',
    careInstructions: 'Wipe with wet cloth. Do not wash.',
    variants: [
      { size: 'Free Size', color: 'Forest Green', colorHex: '#808000', stock: 30, sku: 'GC-BPK-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p55',
    name: "Dino Pattern Knitted Socks Pack",
    slug: 'dino-pattern-knitted-socks-pack',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Pack of 3 pairs of socks with cute knitted dinosaur patterns. Elastic ankle cuffs.",
    longDescription: "Pack of 3 pairs of socks with cute knitted dinosaur patterns. Elastic ankle cuffs. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=800"],
    basePrice: 299,
    rating: 4.6,
    reviewCount: 65,
    soldCount: 108,
    gender: 'boys',
    tags: ["accessories", "socks", "boys", "basics"],
    material: '85% Cotton, 15% Nylon',
    careInstructions: 'Tumble dry low. Machine wash warm.',
    variants: [
      { size: 'Free Size', color: 'Multicolor Dino', colorHex: '#50C878', stock: 120, sku: 'GC-SOK-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 'p56',
    name: "Chiffon Flower Headband Set",
    slug: 'chiffon-flower-headband-set',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Set of 3 charming headbands with silk chiffon flower appliques. Soft elastic band won't leave marks.",
    longDescription: "Set of 3 charming headbands with silk chiffon flower appliques. Soft elastic band won't leave marks. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800"],
    basePrice: 349,
    rating: 4.7,
    reviewCount: 41,
    soldCount: 115,
    gender: 'girls',
    tags: ["accessories", "headband", "girls", "hair"],
    material: 'Chiffon Flowers, Soft Nylon Band',
    careInstructions: 'Gentle hand wash if needed.',
    variants: [
      { size: 'Free Size', color: 'Blush Trio', colorHex: '#DE5D83', stock: 60, sku: 'GC-HDB-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p57',
    name: "Stretchy Unicorn Charm Bracelet",
    slug: 'stretchy-unicorn-charm-bracelet',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Colorful stretchy bracelet with acrylic candy beads and a metal unicorn charm. Lead free.",
    longDescription: "Colorful stretchy bracelet with acrylic candy beads and a metal unicorn charm. Lead free. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800"],
    basePrice: 249,
    rating: 4.6,
    reviewCount: 23,
    soldCount: 122,
    gender: 'girls',
    tags: ["accessories", "jewellery", "girls", "bracelet"],
    material: 'Acrylic Beads, Silver Plated Zinc Charm',
    careInstructions: 'Keep away from water.',
    variants: [
      { size: 'Free Size', color: 'Pastel Rainbow', colorHex: '#FFFFF0', stock: 100, sku: 'GC-BRC-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p58',
    name: "Glitter Frame Polarized Sunglasses",
    slug: 'glitter-frame-polarized-sunglasses',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Cute cat-ear details on glitter frames. Safe polarized lenses protect kids eyes.",
    longDescription: "Cute cat-ear details on glitter frames. Safe polarized lenses protect kids eyes. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800"],
    basePrice: 499,
    rating: 4.5,
    reviewCount: 19,
    soldCount: 129,
    gender: 'girls',
    tags: ["accessories", "eyewear", "girls", "glitter"],
    material: 'Polycarbonate Frame & Lenses',
    careInstructions: 'Wipe with microfiber cloth.',
    variants: [
      { size: 'Free Size', color: 'Glitter Pink', colorHex: '#DE5D83', stock: 75, sku: 'GC-SUN-003' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 'p59',
    name: "Plush Unicorn Zipper Crossbody",
    slug: 'plush-unicorn-zipper-crossbody',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Ultra-soft plush bag with embroidered eyes, metallic horn, and zipper closure. Holds small treasures.",
    longDescription: "Ultra-soft plush bag with embroidered eyes, metallic horn, and zipper closure. Holds small treasures. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800"],
    basePrice: 799,
    rating: 4.8,
    reviewCount: 52,
    soldCount: 136,
    gender: 'girls',
    tags: ["accessories", "bag", "girls", "plush"],
    material: 'Soft Faux-Fur Polyester',
    careInstructions: 'Hand wash cold. Line dry.',
    variants: [
      { size: 'Free Size', color: 'White/Lavender', colorHex: '#FFFFF0', stock: 40, sku: 'GC-BAG-003' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p60',
    name: "Ribbon Bow Alligator Hair Clips",
    slug: 'ribbon-bow-alligator-hair-clips',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Pack of 5 large grosgrain ribbon bow clips on metal alligator clamps. Beautiful colors.",
    longDescription: "Pack of 5 large grosgrain ribbon bow clips on metal alligator clamps. Beautiful colors. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800"],
    basePrice: 399,
    rating: 4.7,
    reviewCount: 41,
    soldCount: 143,
    gender: 'girls',
    tags: ["accessories", "hair-clips", "girls", "basics"],
    material: 'Grosgrain Polyester Ribbon, Iron Clamp',
    careInstructions: 'Avoid crushing. Store flat.',
    variants: [
      { size: 'Free Size', color: 'Bright Assortment', colorHex: '#DE5D83', stock: 85, sku: 'GC-CLP-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 'p61',
    name: "Heavyweight Organic Cotton Hoodie",
    slug: 'heavyweight-organic-cotton-hoodie',
    brand: 'UrbanThreads',
    category: 'Tops',
    categorySlug: 'tops',
    vendor: VENDORS[0]!,
    description: "Ultra-soft heavyweight hoodie crafted from organic cotton and recycled polyester loopback fleece. Unisex regular fit.",
    longDescription: "Ultra-soft heavyweight hoodie crafted from organic cotton and recycled polyester loopback fleece. Unisex regular fit. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"],
    basePrice: 2999,
    rating: 4.8,
    reviewCount: 112,
    soldCount: 150,
    gender: 'unisex',
    tags: ["hoodie", "unisex", "casual", "basics", "organic"],
    material: '80% Organic Cotton, 20% Recycled Polyester',
    careInstructions: 'Machine wash warm. Tumble dry medium.',
    variants: [
      { size: 'S', color: 'Heather Gray', colorHex: '#808080', stock: 25, sku: 'UT-UHD-001-S' },
      { size: 'M', color: 'Heather Gray', colorHex: '#808080', stock: 30, sku: 'UT-UHD-001-M' },
      { size: 'L', color: 'Heather Gray', colorHex: '#808080', stock: 25, sku: 'UT-UHD-001-L' },
      { size: 'XL', color: 'Heather Gray', colorHex: '#808080', stock: 15, sku: 'UT-UHD-001-XL' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'p62',
    name: "Suede Retro Running Sneakers",
    slug: 'suede-retro-running-sneakers',
    brand: 'SoleMate',
    category: 'Footwear',
    categorySlug: 'footwear',
    vendor: VENDORS[2]!,
    description: "Vintage-inspired running sneakers with breathable mesh panels, premium suede overlays, and lightweight EVA cushioning.",
    longDescription: "Vintage-inspired running sneakers with breathable mesh panels, premium suede overlays, and lightweight EVA cushioning. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800"],
    basePrice: 4599,
    rating: 4.7,
    reviewCount: 88,
    soldCount: 157,
    gender: 'unisex',
    tags: ["shoes", "sneakers", "unisex", "retro", "sporty"],
    material: 'Suede and Mesh Upper, Rubber Sole',
    careInstructions: 'Clean with suede brush or damp cloth.',
    variants: [
      { size: '38', color: 'White/Navy', colorHex: '#000080', stock: 15, sku: 'SM-URS-001-38' },
      { size: '40', color: 'White/Navy', colorHex: '#000080', stock: 20, sku: 'SM-URS-001-40' },
      { size: '42', color: 'White/Navy', colorHex: '#000080', stock: 15, sku: 'SM-URS-001-42' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p63',
    name: "Oversized Denim Overshirt",
    slug: 'oversized-denim-overshirt',
    brand: 'UrbanThreads',
    category: 'Shirts',
    categorySlug: 'shirts',
    vendor: VENDORS[0]!,
    description: "Relaxed-fit overshirt in medium wash durable cotton denim. Classic button-down style for layering.",
    longDescription: "Relaxed-fit overshirt in medium wash durable cotton denim. Classic button-down style for layering. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800"],
    basePrice: 2499,
    rating: 4.6,
    reviewCount: 64,
    soldCount: 164,
    gender: 'unisex',
    tags: ["denim", "shirt", "unisex", "oversized", "layering"],
    material: '100% Cotton Denim',
    careInstructions: 'Machine wash cold inside out.',
    variants: [
      { size: 'S', color: 'Indigo Wash', colorHex: '#4B0082', stock: 20, sku: 'UT-UDS-001-S' },
      { size: 'M', color: 'Indigo Wash', colorHex: '#4B0082', stock: 25, sku: 'UT-UDS-001-M' },
      { size: 'L', color: 'Indigo Wash', colorHex: '#4B0082', stock: 20, sku: 'UT-UDS-001-L' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 3),
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 'p64',
    name: "Canvas Street Cargo Pants",
    slug: 'canvas-street-cargo-pants',
    brand: 'UrbanThreads',
    category: 'Denim',
    categorySlug: 'denim',
    vendor: VENDORS[0]!,
    description: "Modern cargo pants with elasticated waistband and drawstrings. Durable canvas fabric with multi-utility pockets.",
    longDescription: "Modern cargo pants with elasticated waistband and drawstrings. Durable canvas fabric with multi-utility pockets. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800"],
    basePrice: 2799,
    rating: 4.5,
    reviewCount: 52,
    soldCount: 171,
    gender: 'unisex',
    tags: ["pants", "cargo", "unisex", "streetwear", "casual"],
    material: '100% Cotton Canvas',
    careInstructions: 'Machine wash cold with similar colors.',
    variants: [
      { size: 'M', color: 'Olive Green', colorHex: '#808000', stock: 20, sku: 'UT-UCJ-001-M' },
      { size: 'L', color: 'Olive Green', colorHex: '#808000', stock: 25, sku: 'UT-UCJ-001-L' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 1),
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 'p65',
    name: "Waterproof TPU Travel Duffle",
    slug: 'waterproof-tpu-travel-duffle',
    brand: 'GlimmerCo',
    category: 'Accessories',
    categorySlug: 'accessories',
    vendor: VENDORS[3]!,
    description: "Rugged and waterproof travel duffle bag with a spacious main compartment, shoe pocket, and adjustable shoulder strap.",
    longDescription: "Rugged and waterproof travel duffle bag with a spacious main compartment, shoe pocket, and adjustable shoulder strap. Made with premium materials and high attention to detail for maximum comfort and style.",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"],
    basePrice: 3499,
    rating: 4.8,
    reviewCount: 47,
    soldCount: 178,
    gender: 'unisex',
    tags: ["accessories", "bag", "unisex", "travel", "waterproof"],
    material: 'Waterproof TPU coated Polyester',
    careInstructions: 'Wipe with damp cloth. Air dry.',
    variants: [
      { size: 'Free Size', color: 'Stealth Black', colorHex: '#1A1A1A', stock: 35, sku: 'GC-UTD-001' }
    ],
    reviews: SAMPLE_REVIEWS.slice(0, 2),
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
  }
];

const ALL_MOCK_REVIEWS: Review[] = [
  { id: 'r1', author: 'Priya M.', avatar: 'P', rating: 5, date: '12 Jul 2026', title: 'Absolutely stunning!', body: 'The fabric quality is incredible. Fits perfectly and the colour is even more beautiful in person. Will definitely order again!', verified: true, helpful: 24 },
  { id: 'r2', author: 'Ananya S.', avatar: 'A', rating: 4, date: '8 Jul 2026', title: 'Great quality, slightly large', body: 'Love the design and fabric but I should have sized down. The details are exquisite though. Customer service was very helpful.', verified: true, helpful: 11 },
  { id: 'r3', author: 'Riya K.', avatar: 'R', rating: 5, date: '3 Jul 2026', title: 'Perfect for festive season', body: 'Ordered this for a wedding and received SO many compliments. The embroidery work is gorgeous. Packaging was also very premium.', verified: true, helpful: 38 },
  { id: 'r4', author: 'Neha T.', avatar: 'N', rating: 4, date: '28 Jun 2026', title: 'Beautiful piece', body: 'Very well made. The stitching is clean and the colours are vibrant. Delivery was faster than expected too!', verified: true, helpful: 7 },
  { id: 'r5', author: 'Sneha G.', avatar: 'S', rating: 5, date: '24 Jun 2026', title: 'Worth every rupee', body: 'Super comfortable fit and elegant design. Premium feel right out of the box!', verified: true, helpful: 15 },
  { id: 'r6', author: 'Kavita P.', avatar: 'K', rating: 3, date: '19 Jun 2026', title: 'Decent quality', body: 'Looks nice, though material is a bit lighter than expected. Fine for casual outings.', verified: true, helpful: 4 },
];

// Derive shortcut fields and variant prices automatically with synced reviews & ratings
export const PRODUCTS: Product[] = RAW_PRODUCTS.map((p, pIdx) => {
  const count = 3 + (pIdx % 2);
  const reviews: Review[] = [];
  let sum = 0;
  for (let i = 0; i < count; i++) {
    const rev = ALL_MOCK_REVIEWS[(pIdx + i) % ALL_MOCK_REVIEWS.length]!;
    reviews.push({
      ...rev,
      id: `rev-${p.id}-${i + 1}`,
    });
    sum += rev.rating;
  }
  const calcRating = Math.round((sum / count) * 10) / 10;

  const localImg = `/images/products/${p.slug}.png`;
  const productImages = [localImg, ...p.images.filter((img) => img !== localImg)];

  return {
    ...p,
    images: productImages,
    rating: calcRating,
    reviewCount: reviews.length,
    reviews,
    vendorId:   p.vendor.id,
    vendorName: p.vendor.name,
    vendorSlug: p.vendor.slug,
    variants: p.variants.map((v) => ({
      ...v,
      price: (v as { price?: number }).price ?? p.basePrice,
    })),
  };
});

// ─── Testimonials ──────────────────────────────────────────────────────────────
export const TESTIMONIALS = [
  { id: 't1', name: 'Aisha Kapoor', role: 'Fashion Blogger', avatar: 'A', rating: 5, text: 'StyleHub has completely transformed how I shop for fashion. The curation is impeccable — I always find something that feels truly special and unique. The quality across all vendors is consistently outstanding.' },
  { id: 't2', name: 'Meera Sharma', role: 'Entrepreneur', avatar: 'M', rating: 5, text: 'As someone who appreciates artisanal fashion, StyleHub is a revelation. I\'ve discovered incredible Indian designers I never would have found otherwise. Every purchase feels like supporting real artistry.' },
  { id: 't3', name: 'Zara Singh', role: 'Content Creator', avatar: 'Z', rating: 5, text: 'The vendor experience is phenomenal. My customers love the product quality and the packaging is so premium — it makes every unboxing feel like a gift. Highly recommend to any fashion-forward shopper.' },
  { id: 't4', name: 'Priya Patel', role: 'Interior Designer', avatar: 'P', rating: 5, text: 'I\'ve been a StyleHub customer for 18 months now. The attention to detail — from curation to delivery — is remarkable. It\'s the only platform where I genuinely trust the quality before I even receive my order.' },
];

// ─── Deals ────────────────────────────────────────────────────────────────────
export const DEALS = [
  { id: 'd1', title: 'Festival Edit', subtitle: 'Up to 40% off ethnic wear', image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&h=400&fit=crop', badge: '40% OFF', cta: 'Shop Now', href: '/products?category=ethnic' },
  { id: 'd2', title: 'New Season Arrivals', subtitle: 'Fresh drops from top vendors', image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=400&fit=crop', badge: 'NEW IN', cta: 'Explore', href: '/products?sort=newest' },
  { id: 'd3', title: 'Artisan Footwear', subtitle: 'Handcrafted luxury for less', image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&h=400&fit=crop', badge: '30% OFF', cta: 'Shop Heels', href: '/products?category=footwear' },
];

// ─── Helper functions ─────────────────────────────────────────────────────────
export const getProductBySlug = (slug: string) =>
  PRODUCTS.find((p) => p.slug === slug);

export const getVendorBySlug = (slug: string) =>
  VENDORS.find((v) => v.slug === slug);

export const getProductsByVendor = (vendorId: string) =>
  PRODUCTS.filter((p) => p.vendor.id === vendorId);

export const getFeaturedProducts = () =>
  PRODUCTS.filter((p) => p.isFeatured);

export const getTrendingProducts = () =>
  [...PRODUCTS].sort((a, b) => b.soldCount - a.soldCount).slice(0, 6);

export const getRelatedProducts = (product: Product, limit = 4) =>
  PRODUCTS.filter((p) => p.categorySlug === product.categorySlug && p.id !== product.id).slice(0, limit);

// Alias used by WishlistClient and other components
export const mockProducts = PRODUCTS;
