const fs = require('fs');
const path = require('path');

const mockPath = path.join(__dirname, '../apps/web/lib/mock-data.ts');
let mock = fs.readFileSync(mockPath, 'utf8');

// Special variant image mappings for color variations generated by Nano Banna:
const VARIANT_IMG_MAPPINGS = [
  {
    slug: 'crimson-banarasi-lehenga-choli',
    colorImages: {
      'Crimson Red': '/images/products/crimson-banarasi-lehenga-choli.png',
      'Rose Gold': '/images/products/crimson-lehenga-choli-set-2.png',
      'Ivory': '/images/products/ivory_anarkali.png'
    }
  },
  {
    slug: 'georgette-bandhani-saree',
    colorImages: {
      'Bandhani Red': '/images/products/georgette-bandhani-saree.png',
      'Teal': '/images/products/teal-bandhani-saree-2.png'
    }
  },
  {
    slug: 'zari-embroidered-anarkali-kurta',
    colorImages: {
      'Ivory': '/images/products/ivory-embroidered-anarkali-kurta-2.png',
      'Mustard': '/images/products/mustard_kurta.png'
    }
  },
  {
    slug: 'geometric-pattern-cotton-kurta',
    colorImages: {
      'Mustard': '/images/products/mustard-block-print-kurta-set-2.png',
      'Indigo': '/images/products/traditional-indigo-block-print-kurta.png'
    }
  },
  {
    slug: 'three-piece-silk-blend-ethnic-set',
    colorImages: {
      'Rose Gold': '/images/products/rose-gold-sharara-set-1.png'
    }
  }
];

// Update RAW_PRODUCTS in mock-data.ts to ensure variants have generated image URLs
VARIANT_IMG_MAPPINGS.forEach(({ slug, colorImages }) => {
  Object.entries(colorImages).forEach(([colorName, imgUrl]) => {
    // Find variant with this color and add image property if not present
    const varRegExp = new RegExp(`({[^}]*color:\\s*['"]${colorName}['"][^}]*)`, 'g');
    mock = mock.replace(varRegExp, (m) => {
      if (!m.includes('image:')) {
        return m.replace(`color: '${colorName}'`, `color: '${colorName}', image: '${imgUrl}'`);
      }
      return m;
    });
  });
});

fs.writeFileSync(mockPath, mock, 'utf8');
console.log('✅ Updated variant images in mock-data.ts');
